FROM rust:latest

#"COUNTRYCODE_PHONENUMBER,COUNTRYCODE_PHONENUMBER"
ARG TW_TO
ENV TW_TO=$TW_TO
#"COUNTRYCODE_PHONENUMBER"
ARG TW_FROM
ENV TW_FROM=$TW_FROM
#"ACCOUNT_SID"
ARG TW_SID
ENV TW_SID=$TW_SID
#"ACCOUNT_TOKEN"
ARG TW_TOKEN
ENV TW_TOKEN=$TW_TOKEN

ENV RUST_BACKTRACE=1

WORKDIR /usr/src/dmv_scheduler
COPY . .
RUN cargo install --path .

CMD ["dmv_scheduler"]